FROM resin/%%RESIN_MACHINE_NAME%%-python

RUN apt-get update && apt-get install -yq \
    git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY . ./

ENV INITSYSTEM on

CMD ["bash", "/usr/src/app/start.sh"]
